version: 0.0
os: linux
files:
  - source: /wordpress/
    destination: /var/www/html/ 
  - source: /wordpress/.db_credentials
    destination: /var/www/html/.db_credentials
    
    # Todo el contenido de tu repositorio (incluyendo la carpeta 'wordpress/', 'scripts/', etc.) 
    # se copiará a /var/www/html/
permissions:
  - object: /var/www/html/
    pattern: "**"
    owner: ec2-user # Ajusta al usuario de tu servidor web (ej. 'www-data' o 'ec2-user')
    group: ec2-user
    type:
      - file
      - directory
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root
